name: FINAL_layer1-bivcd100-char-ENDE-corr
num_runs: 5
epochs: 50
batch_size: 10
optimizer: adam
use_variational_dropout: false
short_cut_connections: false
early_stopping:
  task_name: ComponentIdent
  metric: f1
  patience: 10
character_level_information:
  network_type: LSTM
  dimensionality: 30
  hidden_units: 50
eval_metrics:
- accuracy
- f1
rnn_unit: LSTM
rnn_dropout_input_keep_probability: 0.60
rnn_dropout_output_keep_probability: 0.50
rnn_dropout_state_keep_probability: 0.85
use_bias: true
units: 100
word_dropout_keep_probability: 0.80
embeddings:
- path: /home/eger/wordvecs/bi_shuffle.dim100.punctuation.vec
  gzip: false
  size: 100
tasks:
- name: ComponentIdent
  train_file:
    path: /home/eger/projects/MTCODE/mt-code/experiments/12_tensorflow_port/src/MYDATA/setup/train.en
    column_separator: tab
    word_column: 0
    label_column: 1
    encoding: utf8
  dev_file:
    path: /home/eger/projects/MTCODE/mt-code/experiments/12_tensorflow_port/src/MYDATA/setup/dev.en
    column_separator: tab
    word_column: 0
    label_column: 1
    encoding: utf8
  test_file:
    path: /home/eger/projects/MTCODE/mt-code/experiments/12_tensorflow_port/src/MYDATA/German/ALL/TokenLevel/Test/test.de-en 
    column_separator: tab
    word_column: 0
    label_column: 1
    encoding: utf8
  output_layer: 1
  eval_metrics: []
  classifier: CRF
  encoding: BIO
  dropout_keep_probability: 0.70
